feat: ci changes

diff --git a/.cicd/docker/Dockerfile b/.cicd/docker/Dockerfile
--- a/.cicd/docker/Dockerfile
+++ b/.cicd/docker/Dockerfile
@@ -46,7 +46,10 @@ RUN sampctl build main
 FROM build as run_tests
 
 RUN sampctl build tests
-RUN sampctl run
+RUN if ! sampctl run | grep -q 'ALL TESTS PASSED'; then \
+        echo "::error title=Unit Tests Failed::Check Docker build logs for more information."; \
+        exit 1; \
+    fi
 
 FROM sampctl as runtime
 
diff --git a/.github/workflows/server-ci.yml b/.github/workflows/server-ci.yml
--- a/.github/workflows/server-ci.yml
+++ b/.github/workflows/server-ci.yml
@@ -1,6 +1,6 @@
-name: Build project
+name: server-ci
 
-run-name: Running CI by @${{ github.actor }}
+run-name: Running server-ci by @${{ github.actor }}
 
 on:
   push:
@@ -13,8 +13,8 @@ on:
   workflow_dispatch:
 
 jobs:
-  tests:
-    name: Run tests
+  ci:
+    name: Continuous Integration
     runs-on: ubuntu-latest
     steps:
       - name: Check out the repo
@@ -25,7 +25,7 @@ jobs:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GH_PAT }}
-      - name: Build and push Docker image
+      - name: Run tests
         uses: docker/build-push-action@v3
         with:
           context: .
@@ -34,3 +34,8 @@ jobs:
           build-args: |
             "SAMPCTL_GITHUB_TOKEN=${{ secrets.GH_PAT }}"
           push: false
+      - name: Check if tests passed
+        if: failure()
+        run: |
+          echo "::error title=Unit Tests Failed::Check Docker build logs for more information."
+          exit 1
